# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FindNeighbors_Rcpp <- function(i, X_loc, Y_loc, platform) {
    .Call(`_BINRES_FindNeighbors_Rcpp`, i, X_loc, Y_loc, platform)
}

ComputePottsDist_Rcpp <- function(tmpBeta, c_vec, X_loc, Y_loc, platform) {
    .Call(`_BINRES_ComputePottsDist_Rcpp`, tmpBeta, c_vec, X_loc, Y_loc, platform)
}

UpdateClIds <- function(dpAlpha, pottsBeta, psi1, psi2, geoq, Pi, dpXi, clIds, L1_Ids, L2_Ids, X_loc, Y_loc, platform) {
    .Call(`_BINRES_UpdateClIds`, dpAlpha, pottsBeta, psi1, psi2, geoq, Pi, dpXi, clIds, L1_Ids, L2_Ids, X_loc, Y_loc, platform)
}

UpdateL1 <- function(K1_max, testData1, mu_k, Lambda_k, a_mu, B_mu, d1, R1, psi1, geoq, clIds, L1_Ids) {
    .Call(`_BINRES_UpdateL1`, K1_max, testData1, mu_k, Lambda_k, a_mu, B_mu, d1, R1, psi1, geoq, clIds, L1_Ids)
}

